[versions]
junitVersion = "5.9.0"

[libraries]
automaton = "dk.brics.automaton:automaton:1.11-8"
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitVersion" }
truth = "com.google.truth:truth:1.1.3"
